Repository commercelayer/dashboard-apps, pull requests merged in 2024-10, with the labels that each got.

#75 Sort `Event callbacks` list
  apps/webhooks/src/pages/EventCallbacksList.tsx
Labels: enhancement

#74 Add missing form behavior to `Stock transfers` timeline
  apps/stock_transfers/src/components/StockTransferTimeline.tsx
Labels: bug

#73 Update deps to latest major and uniform apps with new details blocks
  apps/bundles/package.json
  apps/bundles/src/components/BundleInfo.tsx
  apps/bundles/src/pages/BundleDetails.tsx
  apps/customers/package.json
  apps/customers/src/pages/CustomerDetails.tsx
  apps/exports/package.json
  apps/exports/src/components/Details/ExportDetails.tsx
  apps/exports/src/pages/DetailsPage.tsx
  apps/gift_cards/package.json
  apps/gift_cards/src/components/DetailsInfo.tsx
  apps/gift_cards/src/pages/GiftCardDetails.tsx
  apps/gift_cards/src/utils/normalizeLogs.test.ts
  apps/gift_cards/src/utils/normalizeLogs.ts
  apps/imports/package.json
  apps/imports/src/components/Details/ImportDetails.tsx
  apps/imports/src/components/Details/RowParentResource.tsx
  apps/imports/src/pages/DetailsPage.tsx
  apps/inventory/package.json
  apps/inventory/src/pages/StockItemDetails.tsx
  apps/orders/package.json
  apps/orders/src/components/OrderSummary/HeaderActions.tsx
  apps/orders/src/pages/OrderDetails.tsx
  apps/price_lists/package.json
  apps/price_lists/src/pages/PriceDetails.tsx
  apps/promotions/package.json
  apps/promotions/src/pages/PromotionDetailsPage.tsx
  apps/returns/package.json
  apps/returns/src/components/ReturnInfo.tsx
  apps/returns/src/components/Timeline.tsx
  apps/returns/src/pages/ReturnDetails.tsx
  apps/shipments/package.json
  apps/shipments/src/components/ShipmentTimeline.tsx
  apps/shipments/src/hooks/useShipmentToolbar.tsx
  apps/shipments/src/pages/ShipmentDetails.tsx
  apps/sku_lists/package.json
  apps/sku_lists/src/pages/SkuListDetails.tsx
  apps/skus/package.json
  apps/skus/src/pages/SkuDetails.tsx
  apps/stock_transfers/package.json
  apps/stock_transfers/src/components/StockTransferInfo.tsx
  apps/stock_transfers/src/pages/Filters.tsx
  apps/stock_transfers/src/pages/StockTransferDetails.tsx
  apps/stock_transfers/src/pages/StockTransfersList.tsx
  apps/tags/package.json
  apps/tags/src/components/ListItemTag.tsx
  apps/webhooks/package.json
  apps/webhooks/src/components/WebhookInfos.tsx
  apps/webhooks/src/pages/WebhookDetails.tsx
  apps/webhooks/src/pages/WebhookEdit.tsx
  packages/app-builder/package.json
  packages/common/package.json
  packages/index/package.json
  pnpm-lock.yaml
Labels: enhancement

#5 Update include list when exporting shipments
  apps/exports/src/data/relationships.ts
Labels: enhancement

#76 v2.5.0
  apps/bundles/package.json
  apps/customers/package.json
  apps/exports/package.json
  apps/gift_cards/package.json
  apps/imports/package.json
  apps/inventory/package.json
  apps/orders/package.json
  apps/price_lists/package.json
  apps/promotions/package.json
  apps/returns/package.json
  apps/shipments/package.json
  apps/sku_lists/package.json
  apps/skus/package.json
  apps/stock_transfers/package.json
  apps/tags/package.json
  apps/webhooks/package.json
  lerna.json
  packages/app-builder/package.json
  packages/common/package.json
  packages/index/package.json
Labels: ignore-for-release

#77 Update `app-elements` and apply refinements
  apps/bundles/package.json
  apps/customers/package.json
  apps/exports/package.json
  apps/exports/src/pages/DetailsPage.tsx
  apps/gift_cards/package.json
  apps/imports/package.json
  apps/inventory/package.json
  apps/orders/package.json
  apps/price_lists/package.json
  apps/promotions/package.json
  apps/returns/package.json
  apps/returns/src/pages/ReturnDetails.tsx
  apps/shipments/package.json
  apps/shipments/src/components/ShipmentInfo.tsx
  apps/sku_lists/package.json
  apps/skus/package.json
  apps/stock_transfers/package.json
  apps/tags/package.json
  apps/webhooks/package.json
  packages/common/package.json
  packages/index/package.json
  pnpm-lock.yaml
Labels: enhancement

#80 Fix attachment creation in `Stock transfers` app
  apps/stock_transfers/src/components/StockTransferTimeline.tsx
Labels: bug

#83 Fix spacings in some details pages
  apps/bundles/src/pages/BundleDetails.tsx
  apps/orders/src/pages/OrderDetails.tsx
  apps/shipments/src/pages/ShipmentDetails.tsx
  apps/skus/src/pages/SkuDetails.tsx
Labels: bug

#82 Show whether taxes are included or not in the order summary
  apps/orders/src/components/OrderSummary/SummaryRows.tsx
  apps/orders/src/components/OrderSummary/utils.tsx
Labels: bug

#86 v2.5.2
  apps/bundles/package.json
  apps/customers/package.json
  apps/exports/package.json
  apps/gift_cards/package.json
  apps/imports/package.json
  apps/inventory/package.json
  apps/orders/package.json
  apps/price_lists/package.json
  apps/promotions/package.json
  apps/returns/package.json
  apps/shipments/package.json
  apps/sku_lists/package.json
  apps/skus/package.json
  apps/stock_transfers/package.json
  apps/tags/package.json
  apps/webhooks/package.json
  lerna.json
  packages/common/package.json
  packages/index/package.json
Labels: ignore-for-release

#87 Update `app-elements` package
  apps/bundles/package.json
  apps/customers/package.json
  apps/exports/package.json
  apps/gift_cards/package.json
  apps/imports/package.json
  apps/inventory/package.json
  apps/orders/package.json
  apps/price_lists/package.json
  apps/promotions/package.json
  apps/returns/package.json
  apps/shipments/package.json
  apps/sku_lists/package.json
  apps/skus/package.json
  apps/stock_transfers/package.json
  apps/tags/package.json
  apps/webhooks/package.json
  packages/common/package.json
  packages/index/package.json
  pnpm-lock.yaml
Labels: enhancement

#84 Reorganize `SKUs` app detail page with tabs
  apps/skus/src/pages/LinkDetails.tsx
  apps/skus/src/pages/LinkEdit.tsx
  apps/skus/src/pages/LinkNew.tsx
  apps/skus/src/pages/SkuDetails.tsx
  packages/common/src/components/LinkListRow.tsx
  packages/common/src/components/LinkListTable.tsx
Labels: enhancement

#89 Update `app-elements` package to latest version
  apps/bundles/package.json
  apps/customers/package.json
  apps/exports/package.json
  apps/gift_cards/package.json
  apps/imports/package.json
  apps/inventory/package.json
  apps/orders/package.json
  apps/price_lists/package.json
  apps/promotions/package.json
  apps/returns/package.json
  apps/shipments/package.json
  apps/sku_lists/package.json
  apps/skus/package.json
  apps/stock_transfers/package.json
  apps/tags/package.json
  apps/webhooks/package.json
  packages/common/package.json
  packages/index/package.json
  pnpm-lock.yaml
Labels: enhancement

#90 v2.5.4
  apps/bundles/package.json
  apps/customers/package.json
  apps/exports/package.json
  apps/gift_cards/package.json
  apps/imports/package.json
  apps/inventory/package.json
  apps/orders/package.json
  apps/price_lists/package.json
  apps/promotions/package.json
  apps/returns/package.json
  apps/shipments/package.json
  apps/sku_lists/package.json
  apps/skus/package.json
  apps/stock_transfers/package.json
  apps/tags/package.json
  apps/webhooks/package.json
  lerna.json
  packages/common/package.json
  packages/index/package.json
Labels: ignore-for-release

#91 Update app-elements with `useResourceList`
  apps/bundles/package.json
  apps/customers/package.json
  apps/customers/src/pages/CustomerOrders.tsx
  apps/exports/package.json
  apps/gift_cards/package.json
  apps/gift_cards/src/components/ListItemGiftCard.tsx
  apps/imports/package.json
  apps/inventory/package.json
  apps/orders/package.json
  apps/price_lists/package.json
  apps/promotions/package.json
  apps/promotions/src/components/CouponTable.tsx
  apps/promotions/src/hooks/useDeleteCouponOverlay.tsx
  apps/promotions/src/pages/CouponListPage.tsx
  apps/returns/package.json
  apps/shipments/package.json
  apps/sku_lists/package.json
  apps/sku_lists/src/components/SkuListManualItems.tsx
  apps/skus/package.json
  apps/stock_transfers/package.json
  apps/tags/package.json
  apps/tags/src/components/ListItemTag.tsx
  apps/webhooks/package.json
  apps/webhooks/src/components/ListItemEventCallback.tsx
  apps/webhooks/src/components/ListItemWebhook.tsx
  apps/webhooks/src/pages/EventCallbacksList.tsx
  apps/webhooks/src/pages/WebhooksList.tsx
  packages/common/package.json
  packages/index/package.json
  pnpm-lock.yaml
Labels: enhancement

#92 Replace wrongly edited doc link
  apps/skus/src/components/ShippingCategorySelect.tsx
Labels: bug

#93 Update `SKU List` form with new selector
  apps/sku_lists/src/components/SkuListForm/SkuListForm.tsx
  apps/sku_lists/src/components/SkuListForm/schema.ts
  apps/sku_lists/src/components/SkuListForm/utils.ts
  apps/sku_lists/src/components/SkuListManualItems.tsx
  apps/sku_lists/src/hooks/useCreateSkuList.tsx
  apps/sku_lists/src/pages/SkuListEdit.tsx
  apps/sku_lists/src/pages/SkuListNew.tsx
Labels: enhancement

#94 v2.5.5
  apps/bundles/package.json
  apps/customers/package.json
  apps/exports/package.json
  apps/gift_cards/package.json
  apps/imports/package.json
  apps/inventory/package.json
  apps/orders/package.json
  apps/price_lists/package.json
  apps/promotions/package.json
  apps/returns/package.json
  apps/shipments/package.json
  apps/sku_lists/package.json
  apps/skus/package.json
  apps/stock_transfers/package.json
  apps/tags/package.json
  apps/webhooks/package.json
  lerna.json
  packages/common/package.json
  packages/index/package.json
Labels: ignore-for-release

#95 Fix `SKUs` edit form
  apps/skus/src/utils/getSkuFromFormValues.ts
Labels: bug

#99 Update all deps to latest major
  apps/bundles/package.json
  apps/bundles/src/pages/BundleDetails.tsx
  apps/customers/package.json
  apps/customers/src/pages/CustomerDetails.tsx
  apps/exports/package.json
  apps/exports/src/pages/DetailsPage.tsx
  apps/gift_cards/package.json
  apps/gift_cards/src/pages/GiftCardDetails.tsx
  apps/imports/package.json
  apps/imports/src/pages/DetailsPage.tsx
  apps/inventory/package.json
  apps/inventory/src/pages/StockItemDetails.tsx
  apps/orders/package.json
  apps/orders/src/pages/OrderDetails.tsx
  apps/price_lists/package.json
  apps/price_lists/src/pages/PriceDetails.tsx
  apps/promotions/package.json
  apps/promotions/src/pages/PromotionDetailsPage.tsx
  apps/returns/package.json
  apps/returns/src/pages/ReturnDetails.tsx
  apps/shipments/package.json
  apps/shipments/src/pages/ShipmentDetails.tsx
  apps/sku_lists/package.json
  apps/sku_lists/src/pages/SkuListDetails.tsx
  apps/skus/package.json
  apps/skus/src/pages/SkuDetails.tsx
  apps/stock_transfers/package.json
  apps/stock_transfers/src/pages/StockTransferDetails.tsx
  apps/tags/package.json
  apps/webhooks/package.json
  apps/webhooks/src/pages/WebhookDetails.tsx
  packages/common/package.json
  packages/index/package.json
  pnpm-lock.yaml
Labels: enhancement

#98 Hide reserved stock if quantity is `0`
  apps/inventory/src/components/ListItemStockItem.tsx
Labels: bug

#97 Share `SKU description` block between apps
  apps/bundles/package.json
  apps/bundles/src/components/BundleDescription.tsx
  apps/bundles/src/pages/BundleDetails.tsx
  apps/inventory/src/components/SkuDescription.tsx
  apps/inventory/src/pages/StockItemDetails.tsx
  apps/price_lists/src/components/SkuDescription.tsx
  apps/price_lists/src/pages/PriceDetails.tsx
  apps/skus/src/components/SkuDescription.tsx
  apps/skus/src/components/SkuInfo.tsx
  apps/skus/src/pages/SkuDetails.tsx
  packages/common/package.json
  packages/common/src/components/SkuDescription.tsx
  pnpm-lock.yaml
Labels: enhancement

#100 Enhance Items list of `SKU list` app
  apps/sku_lists/src/components/ListItemSkuListItem.tsx
  apps/sku_lists/src/components/SkuListManualItems.tsx
Labels: enhancement

#101 v2.5.6
  apps/bundles/package.json
  apps/customers/package.json
  apps/exports/package.json
  apps/gift_cards/package.json
  apps/imports/package.json
  apps/inventory/package.json
  apps/orders/package.json
  apps/price_lists/package.json
  apps/promotions/package.json
  apps/returns/package.json
  apps/shipments/package.json
  apps/sku_lists/package.json
  apps/skus/package.json
  apps/stock_transfers/package.json
  apps/tags/package.json
  apps/webhooks/package.json
  lerna.json
  packages/common/package.json
  packages/index/package.json
Labels: ignore-for-release

#102 Fix edit form default values in `skus` app
  apps/skus/src/pages/SkuEdit.tsx
Labels: bug

#103 Update dependencies
  apps/bundles/package.json
  apps/customers/package.json
  apps/exports/package.json
  apps/gift_cards/package.json
  apps/imports/package.json
  apps/inventory/package.json
  apps/orders/package.json
  apps/price_lists/package.json
  apps/promotions/package.json
  apps/returns/package.json
  apps/shipments/package.json
  apps/sku_lists/package.json
  apps/sku_lists/src/components/SkuListManualItems.tsx
  apps/skus/package.json
  apps/stock_transfers/package.json
  apps/tags/package.json
  apps/webhooks/package.json
  packages/app-builder/package.json
  packages/common/package.json
  packages/index/package.json
  pnpm-lock.yaml
Labels: enhancement

#104 v2.5.7
  apps/bundles/package.json
  apps/customers/package.json
  apps/exports/package.json
  apps/gift_cards/package.json
  apps/imports/package.json
  apps/inventory/package.json
  apps/orders/package.json
  apps/price_lists/package.json
  apps/promotions/package.json
  apps/returns/package.json
  apps/shipments/package.json
  apps/sku_lists/package.json
  apps/skus/package.json
  apps/stock_transfers/package.json
  apps/tags/package.json
  apps/webhooks/package.json
  lerna.json
  packages/app-builder/package.json
  packages/common/package.json
  packages/index/package.json
Labels: ignore-for-release

#105 Fix types of update form of `skus` app
  apps/skus/src/pages/SkuEdit.tsx
  apps/skus/src/utils/getSkuFromFormValues.ts
Labels: bug

#107 Small improvements to coupons from the promotion app
  apps/promotions/src/data/formConverters/coupon.ts
  apps/promotions/src/pages/PromotionDetailsPage.tsx
Labels: enhancement

#108 Update `app-elements` package to latest
  apps/bundles/package.json
  apps/customers/package.json
  apps/exports/package.json
  apps/gift_cards/package.json
  apps/imports/package.json
  apps/inventory/package.json
  apps/orders/package.json
  apps/price_lists/package.json
  apps/promotions/package.json
  apps/returns/package.json
  apps/shipments/package.json
  apps/sku_lists/package.json
  apps/skus/package.json
  apps/stock_transfers/package.json
  apps/tags/package.json
  apps/webhooks/package.json
  packages/common/package.json
  packages/index/package.json
  pnpm-lock.yaml
Labels: enhancement

#106 Orders - Improve text search logic by detecting email address
  apps/orders/src/data/filters.test.ts
  apps/orders/src/data/filters.ts
Labels: bug

#109 v2.5.8
  apps/bundles/package.json
  apps/customers/package.json
  apps/exports/package.json
  apps/gift_cards/package.json
  apps/imports/package.json
  apps/inventory/package.json
  apps/orders/package.json
  apps/price_lists/package.json
  apps/promotions/package.json
  apps/returns/package.json
  apps/shipments/package.json
  apps/sku_lists/package.json
  apps/skus/package.json
  apps/stock_transfers/package.json
  apps/tags/package.json
  apps/webhooks/package.json
  lerna.json
  packages/common/package.json
  packages/index/package.json
Labels: ignore-for-release

#110 Add support for `tags` in `promotions` app
  apps/promotions/src/pages/PromotionDetailsPage.tsx
Labels: enhancement

#111 v2.5.9
  apps/promotions/package.json
  lerna.json
Labels: ignore-for-release

#112 Update dependencies
  apps/bundles/package.json
  apps/customers/package.json
  apps/exports/package.json
  apps/gift_cards/package.json
  apps/imports/package.json
  apps/inventory/package.json
  apps/orders/package.json
  apps/price_lists/package.json
  apps/promotions/package.json
  apps/returns/package.json
  apps/shipments/package.json
  apps/sku_lists/package.json
  apps/skus/package.json
  apps/stock_transfers/package.json
  apps/tags/package.json
  apps/webhooks/package.json
  packages/app-builder/package.json
  packages/common/package.json
  packages/index/package.json
  pnpm-lock.yaml
Labels: enhancement

#113 v2.5.10
  apps/bundles/package.json
  apps/customers/package.json
  apps/exports/package.json
  apps/gift_cards/package.json
  apps/imports/package.json
  apps/inventory/package.json
  apps/orders/package.json
  apps/price_lists/package.json
  apps/promotions/package.json
  apps/returns/package.json
  apps/shipments/package.json
  apps/sku_lists/package.json
  apps/skus/package.json
  apps/stock_transfers/package.json
  apps/tags/package.json
  apps/webhooks/package.json
  lerna.json
  packages/app-builder/package.json
  packages/common/package.json
  packages/index/package.json
Labels: ignore-for-release

#115 Add `All prices` page in `price_lists` app
  apps/price_lists/src/components/ListItemPrice.tsx
  apps/price_lists/src/components/ListItemSku.tsx
  apps/price_lists/src/components/PriceForm.tsx
  apps/price_lists/src/components/PriceListSelector.tsx
  apps/price_lists/src/data/routes.ts
  apps/price_lists/src/hooks/usePriceDetails.tsx
  apps/price_lists/src/hooks/usePriceListDetails.tsx
  apps/price_lists/src/pages/Home.tsx
  apps/price_lists/src/pages/PriceDetails.tsx
  apps/price_lists/src/pages/PriceEdit.tsx
  apps/price_lists/src/pages/PriceNew.tsx
  apps/price_lists/src/pages/PricesList.tsx
Labels: enhancement

#114 Add `All inventory` page in `inventory` app
  apps/inventory/src/App.tsx
  apps/inventory/src/components/ListItemSku.tsx
  apps/inventory/src/components/ListItemStockItem.tsx
  apps/inventory/src/components/ListItemStockLocation.tsx
  apps/inventory/src/components/StockItemForm.tsx
  apps/inventory/src/components/StockItemInfo.tsx
  apps/inventory/src/components/StockLocationSelector.tsx
  apps/inventory/src/data/filters.ts
  apps/inventory/src/data/routes.ts
  apps/inventory/src/hooks/useStockLocationDetails.tsx
  apps/inventory/src/pages/Home.tsx
  apps/inventory/src/pages/StockItemDetails.tsx
  apps/inventory/src/pages/StockItemEdit.tsx
  apps/inventory/src/pages/StockItemNew.tsx
  apps/inventory/src/pages/StockItemsList.tsx
Labels: enhancement

#116 v2.6.0
  apps/inventory/package.json
  apps/price_lists/package.json
  lerna.json
Labels: ignore-for-release

#119 New order and edit order from orders app can add bundles without a market
  apps/orders/src/components/OrderSummary/hooks/useAddItemOverlay.tsx
Labels: enhancement

#117 Enhance home page of `Price lists` app
  apps/price_lists/src/pages/Home.tsx
Labels: enhancement

#118 Enhance home page of `Inventory` app
  apps/inventory/src/pages/Home.tsx
Labels: enhancement

#120 Update dependencies
  apps/bundles/package.json
  apps/customers/package.json
  apps/exports/package.json
  apps/gift_cards/package.json
  apps/imports/package.json
  apps/inventory/package.json
  apps/orders/package.json
  apps/orders/src/pages/LinkDetails.tsx
  apps/price_lists/package.json
  apps/promotions/package.json
  apps/returns/package.json
  apps/shipments/package.json
  apps/sku_lists/package.json
  apps/skus/package.json
  apps/stock_transfers/package.json
  apps/tags/package.json
  apps/webhooks/package.json
  packages/app-builder/package.json
  packages/common/package.json
  packages/common/src/components/LinkListRow.tsx
  packages/index/package.json
  pnpm-lock.yaml
Labels: enhancement

#123 Use new `ResourcePaymentMethod` for orders and customers apps
  apps/customers/src/components/CustomerWallet.tsx
  apps/customers/src/components/PaymentMethod.tsx
  apps/orders/src/components/OrderPayment.tsx
  apps/orders/src/components/PaymentMethod.tsx
  apps/orders/src/components/RefundForm.tsx
  apps/orders/src/hooks/useCaptureOverlay.tsx
  apps/orders/src/utils/order.ts
Labels: enhancement

#124 v2.6.1
  apps/bundles/package.json
  apps/customers/package.json
  apps/exports/package.json
  apps/gift_cards/package.json
  apps/imports/package.json
  apps/inventory/package.json
  apps/orders/package.json
  apps/price_lists/package.json
  apps/promotions/package.json
  apps/returns/package.json
  apps/shipments/package.json
  apps/sku_lists/package.json
  apps/skus/package.json
  apps/stock_transfers/package.json
  apps/tags/package.json
  apps/webhooks/package.json
  lerna.json
  packages/app-builder/package.json
  packages/common/package.json
  packages/index/package.json
Labels: ignore-for-release

#121 Setup new `Subscription` app
  apps/subscriptions/.env
  apps/subscriptions/.eslintrc.cjs
  apps/subscriptions/.gitignore
  apps/subscriptions/.lintstagedrc.json
  apps/subscriptions/LICENSE
  apps/subscriptions/index.html
  apps/subscriptions/package.json
  apps/subscriptions/public/config.js
  apps/subscriptions/public/config.preview-prd.js
  apps/subscriptions/public/config.preview-stg.js
  apps/subscriptions/src/App.tsx
  apps/subscriptions/src/components/ErrorNotFound.tsx
  apps/subscriptions/src/components/ListItemSubscription.tsx
  apps/subscriptions/src/data/dictionaries.ts
  apps/subscriptions/src/data/routes.ts
  apps/subscriptions/src/env.d.ts
  apps/subscriptions/src/hooks/useOrderSubscriptionDetails.tsx
  apps/subscriptions/src/hooks/useTriggerAttribute.ts
  apps/subscriptions/src/main.tsx
  apps/subscriptions/src/mocks/index.ts
  apps/subscriptions/src/mocks/resource.ts
  apps/subscriptions/src/mocks/resources/orderSubscriptions.ts
  apps/subscriptions/src/pages/SubscriptionsList.tsx
  apps/subscriptions/tsconfig.json
  apps/subscriptions/tsconfig.node.json
  apps/subscriptions/vite.config.js
  pnpm-lock.yaml
Labels: enhancement

#129 Update dependencies
  apps/bundles/package.json
  apps/customers/package.json
  apps/customers/src/components/CustomerAddresses.tsx
  apps/exports/package.json
  apps/gift_cards/package.json
  apps/imports/package.json
  apps/inventory/package.json
  apps/orders/package.json
  apps/orders/src/components/OrderAddresses.tsx
  apps/orders/src/pages/CreateReturn.tsx
  apps/price_lists/package.json
  apps/promotions/package.json
  apps/promotions/src/pages/PromotionDetailsPage.tsx
  apps/returns/package.json
  apps/returns/src/components/ReturnAddresses.tsx
  apps/shipments/package.json
  apps/shipments/src/components/ShipmentAddresses.tsx
  apps/sku_lists/package.json
  apps/skus/package.json
  apps/stock_transfers/package.json
  apps/stock_transfers/src/components/StockTransferAddresses.tsx
  apps/tags/package.json
  apps/webhooks/package.json
  packages/app-builder/package.json
  packages/common/package.json
  packages/index/package.json
  pnpm-lock.yaml
Labels: enhancement

#131 Update app-elements to the latest
  apps/bundles/package.json
  apps/customers/package.json
  apps/exports/package.json
  apps/gift_cards/package.json
  apps/imports/package.json
  apps/inventory/package.json
  apps/orders/package.json
  apps/price_lists/package.json
  apps/promotions/package.json
  apps/returns/package.json
  apps/shipments/package.json
  apps/sku_lists/package.json
  apps/skus/package.json
  apps/stock_transfers/package.json
  apps/tags/package.json
  apps/webhooks/package.json
  packages/common/package.json
  packages/index/package.json
  pnpm-lock.yaml
Labels: ignore-for-release

#127 Possibility to set up the shipping and billing addresses from the order creation page
  apps/orders/src/components/OrderAddresses.tsx
Labels: enhancement

#81 Implement the `RefundEstimator` component and refund from app-returns
  apps/orders/src/components/FormReturn.tsx
  apps/orders/src/components/RefundForm.tsx
  apps/orders/src/pages/Refund.tsx
  apps/returns/package.json
  apps/returns/src/App.tsx
  apps/returns/src/components/ReturnSummary.tsx
  apps/returns/src/components/ReturnTimeline.tsx
  apps/returns/src/data/attachments.ts
  apps/returns/src/data/dictionaries.ts
  apps/returns/src/data/filters.ts
  apps/returns/src/data/routes.ts
  apps/returns/src/hooks/useReturnDetails.tsx
  apps/returns/src/metricsApi/types.d.ts
  apps/returns/src/pages/Refund.tsx
  apps/returns/src/pages/ReturnDetails.tsx
  apps/returns/src/pages/ReturnsList.tsx
  common/LinkForm.tsx
  packages/common/package.json
  packages/common/src/components/RefundEstimator.tsx
  packages/common/src/components/RefundForm.tsx
  packages/common/src/pages/RefundPage.tsx
  pnpm-lock.yaml
Labels: enhancement

#11 Add flex promotions
  apps/promotions/src/components/CouponForm.tsx
  apps/promotions/src/components/ListItemPromotion.tsx
  apps/promotions/src/components/PromotionForm.tsx
  apps/promotions/src/data/filters.ts
  apps/promotions/src/data/formConverters/promotion.ts
  apps/promotions/src/data/promotions/components/PromotionSkuListSelector.tsx
  apps/promotions/src/data/promotions/config.tsx
  apps/promotions/src/data/promotions/configs/flex_promotions.tsx
  apps/promotions/src/data/routes.ts
  apps/promotions/src/data/ruleBuilder/config.tsx
  apps/promotions/src/data/ruleBuilder/currency.tsx
  apps/promotions/src/data/ruleBuilder/form/RuleBuilderForm.tsx
  apps/promotions/src/pages/NewPromotionActivationRulePage.tsx
  apps/promotions/src/pages/NewSelectTypePage.tsx
  apps/promotions/src/pages/PromotionDetailsPage.tsx
  apps/promotions/src/pages/PromotionListPage.tsx
  apps/promotions/src/types.ts
Labels: enhancement

#133 Improve UI/UX for package selector in shipments app
  apps/shipments/src/components/FormPackingFieldPackages.tsx
  apps/shipments/src/components/ShipmentSteps.tsx
  apps/shipments/src/data/packingFormSchema.ts
  apps/shipments/src/hooks/useCreateParcel.tsx
  apps/shipments/src/pages/Packing.tsx
Labels: enhancement

#135 Fix list empty state behavior in `customers` app
  apps/customers/src/components/ListEmptyState.tsx
Labels: bug

#136 Replace static list with ResourceList in inventory and price_lists apps
  apps/inventory/src/pages/Home.tsx
  apps/price_lists/src/pages/Home.tsx
Labels: bug

#137 Refine empty states UI and behavior for `price_lists` app
  apps/price_lists/src/components/ListEmptyStatePrice.tsx
  apps/price_lists/src/pages/Home.tsx
  apps/price_lists/src/pages/PricesList.tsx
Labels: bug

#138 v2.6.3
  apps/customers/package.json
  apps/inventory/package.json
  apps/price_lists/package.json
  lerna.json
Labels: ignore-for-release
