Repository commercelayer/dashboard-apps, pull requests merged in 2024-09, with the labels that each got.

#59 v2.3.5
  apps/bundles/package.json
  apps/customers/package.json
  apps/exports/package.json
  apps/gift_cards/package.json
  apps/imports/package.json
  apps/inventory/package.json
  apps/orders/package.json
  apps/price_lists/package.json
  apps/promotions/package.json
  apps/returns/package.json
  apps/shipments/package.json
  apps/sku_lists/package.json
  apps/skus/package.json
  apps/stock_transfers/package.json
  apps/tags/package.json
  apps/webhooks/package.json
  lerna.json
  packages/common/package.json
  packages/index/package.json
Labels: ignore-for-release

#51 Improve `Customers` app
  apps/customers/src/components/CustomerInfo.tsx
  apps/customers/src/components/CustomerStatus.tsx
  apps/customers/src/hooks/useCustomerDeleteOverlay.tsx
  apps/customers/src/hooks/useCustomerDetails.tsx
  apps/customers/src/hooks/useCustomerOrdersList.tsx
  apps/customers/src/pages/CustomerDetails.tsx
  apps/customers/src/pages/CustomerList.tsx
Labels: enhancement

#52 Enforce `SKU list` app
  apps/sku_lists/src/components/SkuListForm/SkuListForm.tsx
  apps/sku_lists/src/hooks/useSkuListDetails.tsx
  apps/sku_lists/src/pages/SkuListDetails.tsx
  apps/sku_lists/src/pages/SkuListEdit.tsx
Labels: enhancement

#60 Update all dependencies to the latest major
  apps/bundles/package.json
  apps/bundles/src/pages/BundlesList.tsx
  apps/customers/package.json
  apps/customers/src/pages/CustomerList.tsx
  apps/exports/package.json
  apps/gift_cards/package.json
  apps/gift_cards/src/pages/GiftCardList.tsx
  apps/imports/package.json
  apps/inventory/package.json
  apps/inventory/src/hooks/useAddItemOverlay.tsx
  apps/inventory/src/pages/Home.tsx
  apps/inventory/src/pages/StockItemsList.tsx
  apps/orders/package.json
  apps/orders/src/components/NewOrder/SelectMarketStep.tsx
  apps/orders/src/components/OrderSummary/hooks/useAddItemOverlay.tsx
  apps/orders/src/pages/Home.tsx
  apps/orders/src/pages/OrderList.tsx
  apps/price_lists/package.json
  apps/price_lists/src/hooks/useAddItemOverlay.tsx
  apps/price_lists/src/pages/Home.tsx
  apps/price_lists/src/pages/PricesList.tsx
  apps/promotions/package.json
  apps/promotions/src/pages/HomePage.tsx
  apps/promotions/src/pages/PromotionListPage.tsx
  apps/returns/package.json
  apps/returns/src/pages/Home.tsx
  apps/returns/src/pages/ReturnsList.tsx
  apps/shipments/package.json
  apps/shipments/src/pages/Home.tsx
  apps/shipments/src/pages/ShipmentList.tsx
  apps/sku_lists/package.json
  apps/sku_lists/src/hooks/useAddItemOverlay.tsx
  apps/sku_lists/src/pages/SkuListsList.tsx
  apps/skus/package.json
  apps/skus/src/pages/SkusList.tsx
  apps/stock_transfers/package.json
  apps/stock_transfers/src/pages/Home.tsx
  apps/stock_transfers/src/pages/StockTransfersList.tsx
  apps/tags/package.json
  apps/tags/src/pages/TagList.tsx
  apps/webhooks/package.json
  packages/common/package.json
  packages/index/package.json
  pnpm-lock.yaml
Labels: enhancement

#62 Update dependencies
  apps/bundles/package.json
  apps/bundles/src/pages/BundleDetails.tsx
  apps/bundles/src/pages/BundlesList.tsx
  apps/customers/package.json
  apps/customers/src/hooks/useCustomerDeleteOverlay.tsx
  apps/customers/src/pages/CustomerList.tsx
  apps/exports/package.json
  apps/gift_cards/package.json
  apps/gift_cards/src/pages/GiftCardList.tsx
  apps/imports/package.json
  apps/inventory/package.json
  apps/inventory/src/hooks/useAddItemOverlay.tsx
  apps/inventory/src/pages/Home.tsx
  apps/inventory/src/pages/StockItemDetails.tsx
  apps/inventory/src/pages/StockItemsList.tsx
  apps/orders/package.json
  apps/orders/src/components/NewOrder/SelectMarketStep.tsx
  apps/orders/src/components/OrderSummary/hooks/useAddItemOverlay.tsx
  apps/orders/src/pages/Home.tsx
  apps/orders/src/pages/OrderList.tsx
  apps/price_lists/package.json
  apps/price_lists/src/components/TableItemPriceTier.tsx
  apps/price_lists/src/hooks/useAddItemOverlay.tsx
  apps/price_lists/src/pages/Home.tsx
  apps/price_lists/src/pages/PricesList.tsx
  apps/promotions/package.json
  apps/promotions/src/pages/HomePage.tsx
  apps/promotions/src/pages/PromotionListPage.tsx
  apps/returns/package.json
  apps/returns/src/pages/Home.tsx
  apps/returns/src/pages/ReturnsList.tsx
  apps/shipments/package.json
  apps/shipments/src/pages/Home.tsx
  apps/shipments/src/pages/ShipmentList.tsx
  apps/sku_lists/package.json
  apps/sku_lists/src/hooks/useAddItemOverlay.tsx
  apps/sku_lists/src/pages/SkuListDetails.tsx
  apps/sku_lists/src/pages/SkuListsList.tsx
  apps/skus/package.json
  apps/skus/src/pages/SkuDetails.tsx
  apps/skus/src/pages/SkusList.tsx
  apps/stock_transfers/package.json
  apps/stock_transfers/src/pages/Home.tsx
  apps/stock_transfers/src/pages/StockTransfersList.tsx
  apps/tags/package.json
  apps/tags/src/components/ListItemTag.tsx
  apps/tags/src/pages/TagList.tsx
  apps/webhooks/package.json
  packages/common/package.json
  packages/index/package.json
  pnpm-lock.yaml
Labels: bug

#63 v2.3.7
  apps/bundles/package.json
  apps/customers/package.json
  apps/exports/package.json
  apps/gift_cards/package.json
  apps/imports/package.json
  apps/inventory/package.json
  apps/orders/package.json
  apps/price_lists/package.json
  apps/promotions/package.json
  apps/returns/package.json
  apps/shipments/package.json
  apps/sku_lists/package.json
  apps/skus/package.json
  apps/stock_transfers/package.json
  apps/tags/package.json
  apps/webhooks/package.json
  lerna.json
  packages/common/package.json
  packages/index/package.json
Labels: ignore-for-release

#53 Add share link button to `skus` and `sku_lists`
  apps/orders/src/pages/LinkDetails.tsx
  apps/orders/src/pages/OrderDetails.tsx
  apps/sku_lists/src/App.tsx
  apps/sku_lists/src/pages/LinkDetails.tsx
  apps/sku_lists/src/pages/LinkEdit.tsx
  apps/sku_lists/src/pages/LinkList.tsx
  apps/sku_lists/src/pages/SkuListDetails.tsx
  apps/skus/src/App.tsx
  apps/skus/src/pages/LinkDetails.tsx
  apps/skus/src/pages/LinkEdit.tsx
  apps/skus/src/pages/LinkList.tsx
  apps/skus/src/pages/SkuDetails.tsx
  packages/common/src/components/LinkDetailsCard.tsx
  packages/common/src/components/LinkForm.tsx
  packages/common/src/components/LinkListRow.tsx
  packages/common/src/components/LinkListTable.tsx
  packages/common/src/data/routes.ts
  packages/common/src/pages/LinkDetailsPage.tsx
  packages/common/src/pages/LinkEditPage.tsx
  packages/common/src/pages/LinkNewPage.tsx
  packages/common/src/pages/LinksArchivePage.tsx
Labels: enhancement

#64 v2.4.0
  apps/orders/package.json
  apps/sku_lists/package.json
  apps/skus/package.json
  lerna.json
  packages/common/package.json
Labels: ignore-for-release

#65 Add support for `upcoming` status in `Stock Transfers` app
  apps/stock_transfers/src/data/dictionaries.ts
  apps/stock_transfers/src/data/filters.ts
  apps/stock_transfers/src/data/lists.test.ts
  apps/stock_transfers/src/data/lists.ts
  apps/stock_transfers/src/pages/Home.tsx
Labels: enhancement

#66 v2.4.1
  apps/stock_transfers/package.json
  lerna.json
Labels: ignore-for-release

#67 Update all dependencies to the latest major
  apps/bundles/package.json
  apps/bundles/src/pages/BundlesList.tsx
  apps/customers/package.json
  apps/exports/package.json
  apps/gift_cards/package.json
  apps/imports/package.json
  apps/inventory/package.json
  apps/orders/package.json
  apps/price_lists/package.json
  apps/promotions/package.json
  apps/returns/package.json
  apps/shipments/package.json
  apps/sku_lists/package.json
  apps/skus/package.json
  apps/skus/src/pages/SkusList.tsx
  apps/stock_transfers/package.json
  apps/tags/package.json
  apps/webhooks/package.json
  packages/app-builder/package.json
  packages/common/package.json
  packages/index/package.json
  pnpm-lock.yaml
Labels: enhancement

#68 v2.4.2
  apps/bundles/package.json
  apps/customers/package.json
  apps/exports/package.json
  apps/gift_cards/package.json
  apps/imports/package.json
  apps/inventory/package.json
  apps/orders/package.json
  apps/price_lists/package.json
  apps/promotions/package.json
  apps/returns/package.json
  apps/shipments/package.json
  apps/sku_lists/package.json
  apps/skus/package.json
  apps/stock_transfers/package.json
  apps/tags/package.json
  apps/webhooks/package.json
  lerna.json
  packages/app-builder/package.json
  packages/common/package.json
  packages/index/package.json
Labels: ignore-for-release

#70 Sort `Customer` orders by `placed_at`
  apps/customers/src/components/CustomerLastOrders.tsx
  apps/customers/src/hooks/useCustomerOrdersList.tsx
  apps/customers/src/pages/CustomerOrders.tsx
Labels: enhancement

#72 v2.4.3
  apps/customers/package.json
  lerna.json
Labels: ignore-for-release
