Repository commercelayer/dashboard-apps, pull requests merged in 2024-12, with the labels that each got.

#132 Flex promotions code editor
  apps/promotions/src/data/promotions/configs/flex_promotions.tsx
  apps/promotions/src/pages/NewPromotionPage.tsx
  apps/promotions/src/pages/PromotionDetailsPage.tsx
Labels: enhancement

#164 Price list rules with CodeEditor
  apps/price_lists/src/components/PriceListForm.tsx
Labels: enhancement

#166 Enhance orders filters
  apps/orders/src/data/filters.ts
  apps/orders/src/pages/Filters.tsx
  apps/orders/src/pages/OrderList.tsx
Labels: enhancement

#167 v2.10.0
  apps/bundles/package.json
  apps/customers/package.json
  apps/exports/package.json
  apps/gift_cards/package.json
  apps/imports/package.json
  apps/inventory/package.json
  apps/orders/package.json
  apps/price_lists/package.json
  apps/promotions/package.json
  apps/returns/package.json
  apps/shipments/package.json
  apps/sku_lists/package.json
  apps/skus/package.json
  apps/stock_transfers/package.json
  apps/subscriptions/package.json
  apps/tags/package.json
  apps/webhooks/package.json
  lerna.json
  packages/common/package.json
  packages/index/package.json
Labels: ignore-for-release

#169 v2.10.1
  apps/bundles/package.json
  apps/orders/package.json
  apps/returns/package.json
  apps/sku_lists/package.json
  apps/skus/package.json
  lerna.json
  packages/common/package.json
  packages/index/package.json
Labels: ignore-for-release

#170 Add tests for dependencies
  packages/index/package.json
  packages/index/src/dependencies.test.ts
  pnpm-lock.yaml
Labels: ignore-for-release

#171 Update `price_tiers` form schema
  apps/price_lists/src/components/PriceTierForm/PriceTierForm.tsx
  apps/price_lists/src/components/PriceTierForm/schema.ts
  apps/price_lists/src/pages/PriceTierEdit.tsx
  apps/price_lists/src/utils/priceTiers.test.ts
  apps/price_lists/src/utils/priceTiers.ts
Labels: bug

#172 Improve validation schema for input with type number in promotion forms
  apps/promotions/src/data/formConverters/coupon.ts
  apps/promotions/src/data/promotions/configs/buy_x_pay_y_promotions.tsx
Labels: bug

#173 Replace static coupon table with `ResourceList` in app-promotions
  apps/promotions/src/components/CouponForm.tsx
  apps/promotions/src/components/CouponTable.tsx
  apps/promotions/src/pages/CouponListPage.tsx
Labels: bug

#175 v2.10.2
  apps/bundles/package.json
  apps/customers/package.json
  apps/exports/package.json
  apps/gift_cards/package.json
  apps/imports/package.json
  apps/inventory/package.json
  apps/orders/package.json
  apps/price_lists/package.json
  apps/promotions/package.json
  apps/returns/package.json
  apps/shipments/package.json
  apps/sku_lists/package.json
  apps/skus/package.json
  apps/stock_transfers/package.json
  apps/subscriptions/package.json
  apps/tags/package.json
  apps/webhooks/package.json
  lerna.json
  packages/app-builder/package.json
  packages/common/package.json
  packages/index/package.json
Labels: ignore-for-release

#176 Restore previous version of react-hook-form
  apps/bundles/package.json
  apps/customers/package.json
  apps/exports/package.json
  apps/gift_cards/package.json
  apps/inventory/package.json
  apps/orders/package.json
  apps/price_lists/package.json
  apps/promotions/package.json
  apps/returns/package.json
  apps/shipments/package.json
  apps/sku_lists/package.json
  apps/skus/package.json
  apps/stock_transfers/package.json
  apps/subscriptions/package.json
  apps/tags/package.json
  apps/webhooks/package.json
  packages/common/package.json
  pnpm-lock.yaml
Labels: bug

#177 v2.10.3
  apps/bundles/package.json
  apps/customers/package.json
  apps/exports/package.json
  apps/gift_cards/package.json
  apps/inventory/package.json
  apps/orders/package.json
  apps/price_lists/package.json
  apps/promotions/package.json
  apps/returns/package.json
  apps/shipments/package.json
  apps/sku_lists/package.json
  apps/skus/package.json
  apps/stock_transfers/package.json
  apps/subscriptions/package.json
  apps/tags/package.json
  apps/webhooks/package.json
  lerna.json
  packages/common/package.json
Labels: ignore-for-release

#179 Update app-elements
  apps/bundles/package.json
  apps/customers/package.json
  apps/exports/package.json
  apps/gift_cards/package.json
  apps/imports/package.json
  apps/inventory/package.json
  apps/orders/package.json
  apps/price_lists/package.json
  apps/promotions/package.json
  apps/returns/package.json
  apps/shipments/package.json
  apps/sku_lists/package.json
  apps/skus/package.json
  apps/stock_transfers/package.json
  apps/subscriptions/package.json
  apps/tags/package.json
  apps/webhooks/package.json
  packages/common/package.json
  packages/index/package.json
  pnpm-lock.yaml
Labels: enhancement

#180 v2.10.4
  apps/bundles/package.json
  apps/customers/package.json
  apps/exports/package.json
  apps/gift_cards/package.json
  apps/imports/package.json
  apps/inventory/package.json
  apps/orders/package.json
  apps/price_lists/package.json
  apps/promotions/package.json
  apps/returns/package.json
  apps/shipments/package.json
  apps/sku_lists/package.json
  apps/skus/package.json
  apps/stock_transfers/package.json
  apps/subscriptions/package.json
  apps/tags/package.json
  apps/webhooks/package.json
  lerna.json
  packages/common/package.json
  packages/index/package.json
Labels: ignore-for-release

#182 Enhance SKU creation behavior
  apps/skus/src/pages/SkuNew.tsx
Labels: bug

#183 v2.10.5
  apps/skus/package.json
  lerna.json
Labels: ignore-for-release
