Repository commercelayer/dashboard-apps, pull requests merged in 2025-04, with the labels that each got.

#250 Update `vite.config.ts` react versions when updating deps
  apps/bundles/package.json
  apps/customers/package.json
  apps/exports/package.json
  apps/gift_cards/package.json
  apps/imports/package.json
  apps/inventory/package.json
  apps/orders/package.json
  apps/price_lists/package.json
  apps/promotions/package.json
  apps/returns/package.json
  apps/shipments/package.json
  apps/sku_lists/package.json
  apps/skus/package.json
  apps/stock_transfers/package.json
  apps/subscriptions/package.json
  apps/tags/package.json
  apps/webhooks/package.json
  package.json
  packages/app-builder/vite.config.js
  packages/common/package.json
  packages/index/.lintstagedrc.json
  packages/index/package.json
  pnpm-lock.yaml
  replace-react.mjs
Labels: enhancement

#251 v3.3.2
  apps/bundles/package.json
  apps/customers/package.json
  apps/exports/package.json
  apps/gift_cards/package.json
  apps/imports/package.json
  apps/inventory/package.json
  apps/orders/package.json
  apps/price_lists/package.json
  apps/promotions/package.json
  apps/returns/package.json
  apps/shipments/package.json
  apps/sku_lists/package.json
  apps/skus/package.json
  apps/stock_transfers/package.json
  apps/subscriptions/package.json
  apps/tags/package.json
  apps/webhooks/package.json
  lerna.json
  packages/app-builder/package.json
  packages/common/package.json
  packages/index/package.json
Labels: ignore-for-release

#249 Add customer anonymization process
  apps/bundles/package.json
  apps/customers/package.json
  apps/customers/src/components/CustomerAnonymization.tsx
  apps/customers/src/hooks/useCustomerCanBeAnonymized.tsx
  apps/customers/src/hooks/useCustomerCanBeDeleted.tsx
  apps/customers/src/hooks/useCustomerDeleteOverlay.tsx
  apps/customers/src/hooks/useCustomerDetails.tsx
  apps/customers/src/pages/CustomerDetails.tsx
  apps/exports/package.json
  apps/gift_cards/package.json
  apps/imports/package.json
  apps/inventory/package.json
  apps/orders/package.json
  apps/price_lists/package.json
  apps/promotions/package.json
  apps/returns/package.json
  apps/shipments/package.json
  apps/sku_lists/package.json
  apps/skus/package.json
  apps/stock_transfers/package.json
  apps/subscriptions/package.json
  apps/tags/package.json
  apps/webhooks/package.json
  packages/common/package.json
  packages/index/package.json
  pnpm-lock.yaml
Labels: enhancement

#256 Fix anonymize visibility
  apps/customers/src/hooks/useCustomerCanBeAnonymized.tsx
Labels: bug

#257 v3.4.1
  apps/customers/package.json
  lerna.json
  packages/index/package.json
Labels: ignore-for-release

#255 `app-exports` improvements
  apps/exports/@typing/Resources.d.ts
  apps/exports/src/components/Form/Filters/InStockSubscriptions.tsx
  apps/exports/src/components/Form/Filters/Orders.tsx
  apps/exports/src/components/Form/Filters/Returns.tsx
  apps/exports/src/components/Form/Filters/index.tsx
  apps/exports/src/components/Form/types.d.ts
  apps/exports/src/data/relationships.ts
  apps/exports/src/data/resources.ts
Labels: enhancement

#260 v3.5.0
  apps/exports/package.json
  lerna.json
Labels: ignore-for-release
