Repository commercelayer/dashboard-apps, pull requests merged in 2025-03, with the labels that each got.

#226 Manage coupon code min and max length with organization flag
  apps/promotions/src/components/CouponForm.tsx
Labels: enhancement

#227 v3.0.2
  apps/promotions/package.json
  apps/shipments/package.json
  lerna.json
Labels: ignore-for-release

#228 Fix names of coupon code length flags
  apps/promotions/src/components/CouponForm.tsx
  apps/promotions/src/data/formConverters/coupon.ts
Labels: bug

#229 v3.0.3
  apps/promotions/package.json
  lerna.json
Labels: ignore-for-release

#230 Update deps to latest minor
  apps/bundles/package.json
  apps/customers/package.json
  apps/exports/package.json
  apps/gift_cards/package.json
  apps/imports/package.json
  apps/inventory/package.json
  apps/orders/package.json
  apps/price_lists/package.json
  apps/promotions/package.json
  apps/returns/package.json
  apps/shipments/package.json
  apps/sku_lists/package.json
  apps/skus/package.json
  apps/stock_transfers/package.json
  apps/subscriptions/package.json
  apps/tags/package.json
  apps/webhooks/package.json
  package.json
  packages/common/package.json
  packages/index/package.json
  pnpm-lock.yaml
Labels: enhancement, dependencies

#231 v3.1.0
  apps/bundles/package.json
  apps/customers/package.json
  apps/exports/package.json
  apps/gift_cards/package.json
  apps/imports/package.json
  apps/inventory/package.json
  apps/orders/package.json
  apps/price_lists/package.json
  apps/promotions/package.json
  apps/returns/package.json
  apps/shipments/package.json
  apps/sku_lists/package.json
  apps/skus/package.json
  apps/stock_transfers/package.json
  apps/subscriptions/package.json
  apps/tags/package.json
  apps/webhooks/package.json
  lerna.json
  packages/common/package.json
  packages/index/package.json
Labels: ignore-for-release

#232 Add additional labels to github release
  .github/release.yaml
Labels: ignore-for-release

#233 Define `i18n` types for all apps
  apps/bundles/i18n.d.ts
  apps/bundles/package.json
  apps/bundles/tsconfig.json
  apps/customers/i18n.d.ts
  apps/customers/package.json
  apps/customers/tsconfig.json
  apps/exports/i18n.d.ts
  apps/exports/package.json
  apps/exports/tsconfig.json
  apps/gift_cards/i18n.d.ts
  apps/gift_cards/package.json
  apps/gift_cards/tsconfig.json
  apps/imports/i18n.d.ts
  apps/imports/package.json
  apps/imports/tsconfig.json
  apps/inventory/i18n.d.ts
  apps/inventory/package.json
  apps/inventory/tsconfig.json
  apps/orders/i18n.d.ts
  apps/orders/package.json
  apps/orders/tsconfig.json
  apps/price_lists/i18n.d.ts
  apps/price_lists/package.json
  apps/price_lists/tsconfig.json
  apps/promotions/i18n.d.ts
  apps/promotions/package.json
  apps/promotions/tsconfig.json
  apps/returns/i18n.d.ts
  apps/returns/package.json
  apps/returns/tsconfig.json
  apps/shipments/i18n.d.ts
  apps/shipments/package.json
  apps/shipments/tsconfig.json
  apps/sku_lists/i18n.d.ts
  apps/sku_lists/package.json
  apps/sku_lists/tsconfig.json
  apps/skus/i18n.d.ts
  apps/skus/package.json
  apps/skus/tsconfig.json
  apps/stock_transfers/i18n.d.ts
  apps/stock_transfers/package.json
  apps/stock_transfers/tsconfig.json
  apps/subscriptions/i18n.d.ts
  apps/subscriptions/package.json
  apps/subscriptions/tsconfig.json
  apps/tags/i18n.d.ts
  apps/tags/package.json
  apps/tags/tsconfig.json
  apps/webhooks/i18n.d.ts
  apps/webhooks/package.json
  apps/webhooks/tsconfig.json
  packages/common/i18n.d.ts
  packages/common/package.json
  packages/common/tsconfig.json
  packages/index/package.json
  pnpm-lock.yaml
Labels: enhancement

#234 Update deps and apply searchbar margin fix
  apps/bundles/package.json
  apps/customers/package.json
  apps/exports/package.json
  apps/gift_cards/package.json
  apps/imports/package.json
  apps/inventory/package.json
  apps/inventory/src/pages/Home.tsx
  apps/orders/package.json
  apps/price_lists/package.json
  apps/price_lists/src/pages/Home.tsx
  apps/promotions/package.json
  apps/promotions/src/pages/CouponListPage.tsx
  apps/returns/package.json
  apps/shipments/package.json
  apps/sku_lists/package.json
  apps/skus/package.json
  apps/stock_transfers/package.json
  apps/subscriptions/package.json
  apps/tags/package.json
  apps/webhooks/package.json
  packages/app-builder/package.json
  packages/common/package.json
  packages/index/package.json
  pnpm-lock.yaml
Labels: enhancement

#235 Bump elements
  apps/bundles/package.json
  apps/customers/package.json
  apps/exports/package.json
  apps/gift_cards/package.json
  apps/imports/package.json
  apps/inventory/package.json
  apps/orders/package.json
  apps/price_lists/package.json
  apps/promotions/package.json
  apps/returns/package.json
  apps/shipments/package.json
  apps/sku_lists/package.json
  apps/skus/package.json
  apps/stock_transfers/package.json
  apps/subscriptions/package.json
  apps/tags/package.json
  apps/webhooks/package.json
  packages/common/package.json
  packages/index/package.json
  pnpm-lock.yaml
Labels: enhancement

#236 v3.1.1
  apps/bundles/package.json
  apps/customers/package.json
  apps/exports/package.json
  apps/gift_cards/package.json
  apps/imports/package.json
  apps/inventory/package.json
  apps/orders/package.json
  apps/price_lists/package.json
  apps/promotions/package.json
  apps/returns/package.json
  apps/shipments/package.json
  apps/sku_lists/package.json
  apps/skus/package.json
  apps/stock_transfers/package.json
  apps/subscriptions/package.json
  apps/tags/package.json
  apps/webhooks/package.json
  lerna.json
  packages/app-builder/package.json
  packages/common/package.json
  packages/index/package.json
Labels: ignore-for-release

#237 Avoid using `name` and `image_url` from sku (`stock_line_items`)
  apps/shipments/src/components/FormPackingFieldItems.tsx
Labels: bug

#238 Distribute discount
  apps/gift_cards/src/components/DetailsInfo.tsx
  apps/gift_cards/src/components/Form.tsx
  apps/imports/src/components/InputParser/schemas/giftCards.ts
  apps/imports/src/components/InputParser/templates/giftCards.ts
Labels: enhancement

#239 v3.2.0
  apps/gift_cards/package.json
  apps/imports/package.json
  apps/shipments/package.json
  lerna.json
Labels: ignore-for-release

#242 v3.2.1
  apps/orders/package.json
  lerna.json
Labels: ignore-for-release

#243 Enhance coupon code min length in validation error
  apps/bundles/package.json
  apps/customers/package.json
  apps/exports/package.json
  apps/gift_cards/package.json
  apps/imports/package.json
  apps/inventory/package.json
  apps/orders/package.json
  apps/orders/src/components/OrderSummary/hooks/useAddCouponOverlay.tsx
  apps/price_lists/package.json
  apps/promotions/package.json
  apps/returns/package.json
  apps/shipments/package.json
  apps/sku_lists/package.json
  apps/skus/package.json
  apps/stock_transfers/package.json
  apps/subscriptions/package.json
  apps/tags/package.json
  apps/webhooks/package.json
  packages/common/package.json
  packages/index/package.json
  pnpm-lock.yaml
Labels: enhancement

#244 v3.2.2
  apps/bundles/package.json
  apps/customers/package.json
  apps/exports/package.json
  apps/gift_cards/package.json
  apps/imports/package.json
  apps/inventory/package.json
  apps/orders/package.json
  apps/price_lists/package.json
  apps/promotions/package.json
  apps/returns/package.json
  apps/shipments/package.json
  apps/sku_lists/package.json
  apps/skus/package.json
  apps/stock_transfers/package.json
  apps/subscriptions/package.json
  apps/tags/package.json
  apps/webhooks/package.json
  lerna.json
  packages/common/package.json
  packages/index/package.json
Labels: ignore-for-release

#240 Add optional stock location selection in links scope configuration
  packages/common/src/components/LinkForm.tsx
  packages/common/src/pages/LinkEditPage.tsx
  packages/common/src/pages/LinkNewPage.tsx
Labels: enhancement

#245 v3.3.0
  apps/bundles/package.json
  apps/orders/package.json
  apps/returns/package.json
  apps/sku_lists/package.json
  apps/skus/package.json
  lerna.json
  packages/common/package.json
Labels: ignore-for-release

#246 Update deps to latest major version
  apps/bundles/package.json
  apps/customers/package.json
  apps/exports/package.json
  apps/gift_cards/package.json
  apps/imports/package.json
  apps/inventory/package.json
  apps/orders/package.json
  apps/price_lists/package.json
  apps/promotions/package.json
  apps/returns/package.json
  apps/shipments/package.json
  apps/sku_lists/package.json
  apps/skus/package.json
  apps/stock_transfers/package.json
  apps/subscriptions/package.json
  apps/subscriptions/src/components/SubscriptionSteps.tsx
  apps/tags/package.json
  apps/webhooks/package.json
  package.json
  packages/app-builder/package.json
  packages/common/package.json
  packages/index/package.json
  pnpm-lock.yaml
Labels: dependencies

#247 Remove checkout link button for orders with private market
  apps/orders/src/pages/OrderDetails.tsx
Labels: bug

#248 v3.3.1
  apps/bundles/package.json
  apps/customers/package.json
  apps/exports/package.json
  apps/gift_cards/package.json
  apps/imports/package.json
  apps/inventory/package.json
  apps/orders/package.json
  apps/price_lists/package.json
  apps/promotions/package.json
  apps/returns/package.json
  apps/shipments/package.json
  apps/sku_lists/package.json
  apps/skus/package.json
  apps/stock_transfers/package.json
  apps/subscriptions/package.json
  apps/tags/package.json
  apps/webhooks/package.json
  lerna.json
  packages/app-builder/package.json
  packages/common/package.json
  packages/index/package.json
Labels: ignore-for-release
