Repository commercelayer/dashboard-apps, pull requests merged in 2025-06, with the labels that each got.

#271 Add `transaction.refused` event
  apps/webhooks/src/data/events.ts
Labels: enhancement

#270 Allow to add multiple SKU list items with one selection
  apps/bundles/package.json
  apps/customers/package.json
  apps/exports/package.json
  apps/gift_cards/package.json
  apps/imports/package.json
  apps/inventory/package.json
  apps/my_sample_app/package.json
  apps/orders/package.json
  apps/price_lists/package.json
  apps/promotions/package.json
  apps/returns/package.json
  apps/shipments/package.json
  apps/sku_lists/package.json
  apps/sku_lists/src/App.tsx
  apps/sku_lists/src/components/ListItemSku.tsx
  apps/sku_lists/src/components/SkuListManualItems.tsx
  apps/sku_lists/src/data/routes.ts
  apps/sku_lists/src/hooks/useAddItemOverlay.tsx
  apps/sku_lists/src/pages/SkuListDetailsAddItems.tsx
  apps/skus/package.json
  apps/stock_transfers/package.json
  apps/subscriptions/package.json
  apps/tags/package.json
  apps/webhooks/package.json
  packages/common/package.json
  packages/index/package.json
  pnpm-lock.yaml
Labels: enhancement

#276 v3.7.0
  apps/bundles/package.json
  apps/customers/package.json
  apps/exports/package.json
  apps/gift_cards/package.json
  apps/imports/package.json
  apps/inventory/package.json
  apps/my_sample_app/package.json
  apps/orders/package.json
  apps/price_lists/package.json
  apps/promotions/package.json
  apps/returns/package.json
  apps/shipments/package.json
  apps/sku_lists/package.json
  apps/skus/package.json
  apps/stock_transfers/package.json
  apps/subscriptions/package.json
  apps/tags/package.json
  apps/webhooks/package.json
  lerna.json
  packages/common/package.json
  packages/index/package.json
Labels: ignore-for-release

#267 Handle async capture in order details
  apps/orders/src/components/OrderSummary/hooks/useActionButtons.tsx
  apps/orders/src/hooks/useOrderDetails.tsx
Labels: enhancement

#280 v3.8.0
  apps/bundles/package.json
  apps/customers/package.json
  apps/exports/package.json
  apps/gift_cards/package.json
  apps/imports/package.json
  apps/inventory/package.json
  apps/my_sample_app/package.json
  apps/orders/package.json
  apps/price_lists/package.json
  apps/promotions/package.json
  apps/returns/package.json
  apps/shipments/package.json
  apps/sku_lists/package.json
  apps/skus/package.json
  apps/stock_transfers/package.json
  apps/subscriptions/package.json
  apps/tags/package.json
  apps/webhooks/package.json
  lerna.json
  packages/common/package.json
  packages/index/package.json
Labels: ignore-for-release

#283 Improve filters instructions
  apps/customers/src/data/filters.ts
  apps/price_lists/src/data/filters.ts
  apps/returns/src/data/filters.ts
Labels: enhancement

#284 UI improvements in app-imports
  apps/imports/src/components/Details/ImportDate.tsx
  apps/imports/src/components/Details/ImportDetails.tsx
  apps/imports/src/components/InputParser/templates/coupon.ts
  apps/imports/src/components/InputParser/templates/skuListItems.ts
  apps/imports/src/components/List/Item.tsx
  apps/imports/src/components/List/ItemDescriptionLine.tsx
  apps/imports/src/components/List/utils.test.ts
  apps/imports/src/components/List/utils.ts
  apps/imports/src/pages/DetailsPage.tsx
Labels: enhancement

#287 v3.8.1
  apps/bundles/package.json
  apps/customers/package.json
  apps/exports/package.json
  apps/gift_cards/package.json
  apps/imports/package.json
  apps/inventory/package.json
  apps/my_sample_app/package.json
  apps/orders/package.json
  apps/price_lists/package.json
  apps/promotions/package.json
  apps/returns/package.json
  apps/shipments/package.json
  apps/sku_lists/package.json
  apps/skus/package.json
  apps/stock_transfers/package.json
  apps/subscriptions/package.json
  apps/tags/package.json
  apps/webhooks/package.json
  lerna.json
  packages/common/package.json
  packages/index/package.json
Labels: ignore-for-release

#290 Add new anonymizations events to `webhooks` app
  apps/webhooks/@typing/Resources.d.ts
  apps/webhooks/src/data/events.ts
Labels: enhancement

#291 v3.8.2
  apps/subscriptions/package.json
  apps/webhooks/package.json
  lerna.json
Labels: ignore-for-release

#293 Add ability to duplicate a flex promotion
  apps/promotions/src/pages/PromotionDetailsPage.tsx
Labels: documentation, enhancement

#292 Allow to filter orders by country
  apps/orders/src/data/filters.ts
  apps/orders/src/metricsApi/useCountryCodes.ts
  apps/orders/src/pages/Filters.tsx
  apps/orders/src/pages/OrderList.tsx
Labels: enhancement

#288 App shipments improvements (filters lists, show reference and packing form adjustments)
  apps/bundles/package.json
  apps/customers/package.json
  apps/exports/package.json
  apps/gift_cards/package.json
  apps/imports/package.json
  apps/inventory/package.json
  apps/my_sample_app/package.json
  apps/orders/package.json
  apps/price_lists/package.json
  apps/promotions/package.json
  apps/returns/package.json
  apps/shipments/package.json
  apps/shipments/src/components/FormPackingFieldPackages.tsx
  apps/shipments/src/components/FormPackingFieldWeight.tsx
  apps/shipments/src/data/filters.ts
  apps/shipments/src/pages/Filters.tsx
  apps/shipments/src/pages/Home.tsx
  apps/shipments/src/pages/ShipmentList.tsx
  apps/sku_lists/package.json
  apps/skus/package.json
  apps/stock_transfers/package.json
  apps/subscriptions/package.json
  apps/tags/package.json
  apps/webhooks/package.json
  packages/common/package.json
  packages/index/package.json
  pnpm-lock.yaml
Labels: enhancement
