Repository commercelayer/dashboard-apps, pull requests merged in 2025-01, with the labels that each got.

#184 Hide SKU list selection when editing a bundle
  apps/bundles/src/components/BundleForm.tsx
Labels: bug

#185 Update app-elements package
  apps/bundles/package.json
  apps/customers/package.json
  apps/exports/package.json
  apps/gift_cards/package.json
  apps/imports/package.json
  apps/inventory/package.json
  apps/orders/package.json
  apps/price_lists/package.json
  apps/promotions/package.json
  apps/returns/package.json
  apps/shipments/package.json
  apps/sku_lists/package.json
  apps/skus/package.json
  apps/stock_transfers/package.json
  apps/subscriptions/package.json
  apps/tags/package.json
  apps/webhooks/package.json
  packages/common/package.json
  packages/index/package.json
  pnpm-lock.yaml
Labels: enhancement

#186 v2.10.6
  apps/bundles/package.json
  apps/customers/package.json
  apps/exports/package.json
  apps/gift_cards/package.json
  apps/imports/package.json
  apps/inventory/package.json
  apps/orders/package.json
  apps/price_lists/package.json
  apps/promotions/package.json
  apps/returns/package.json
  apps/shipments/package.json
  apps/sku_lists/package.json
  apps/skus/package.json
  apps/stock_transfers/package.json
  apps/subscriptions/package.json
  apps/tags/package.json
  apps/webhooks/package.json
  lerna.json
  packages/common/package.json
  packages/index/package.json
Labels: ignore-for-release

#187 v2.11.0
  apps/bundles/package.json
  apps/customers/package.json
  apps/exports/package.json
  apps/gift_cards/package.json
  apps/imports/package.json
  apps/inventory/package.json
  apps/orders/package.json
  apps/price_lists/package.json
  apps/promotions/package.json
  apps/returns/package.json
  apps/shipments/package.json
  apps/sku_lists/package.json
  apps/skus/package.json
  apps/stock_transfers/package.json
  apps/subscriptions/package.json
  apps/tags/package.json
  apps/webhooks/package.json
  lerna.json
  packages/common/package.json
  packages/index/package.json
Labels: ignore-for-release

#189 Set correct order to mount `I18NProvider` in `app-shipments`
  apps/shipments/src/main.tsx
Labels: bug

#188 Enable keyboard quantity selection for SKU lists items
  apps/sku_lists/src/components/ListItemSkuListItem.tsx
Labels: enhancement

#190 Update app-elements to latest major
  apps/bundles/package.json
  apps/customers/package.json
  apps/exports/package.json
  apps/gift_cards/package.json
  apps/imports/package.json
  apps/inventory/package.json
  apps/orders/package.json
  apps/price_lists/package.json
  apps/promotions/package.json
  apps/returns/package.json
  apps/shipments/package.json
  apps/sku_lists/package.json
  apps/skus/package.json
  apps/stock_transfers/package.json
  apps/subscriptions/package.json
  apps/tags/package.json
  apps/webhooks/package.json
  packages/common/package.json
  packages/index/package.json
  pnpm-lock.yaml
Labels: enhancement

#193 Update app-elements to enable new shipment list items
  apps/bundles/package.json
  apps/customers/package.json
  apps/exports/package.json
  apps/gift_cards/package.json
  apps/imports/package.json
  apps/inventory/package.json
  apps/orders/package.json
  apps/orders/src/hooks/useOrderDetails.tsx
  apps/price_lists/package.json
  apps/promotions/package.json
  apps/returns/package.json
  apps/shipments/package.json
  apps/shipments/src/pages/ShipmentList.tsx
  apps/sku_lists/package.json
  apps/skus/package.json
  apps/stock_transfers/package.json
  apps/subscriptions/package.json
  apps/tags/package.json
  apps/webhooks/package.json
  packages/common/package.json
  packages/index/package.json
  pnpm-lock.yaml
Labels: enhancement

#195 v2.11.2
  apps/bundles/package.json
  apps/customers/package.json
  apps/exports/package.json
  apps/gift_cards/package.json
  apps/imports/package.json
  apps/inventory/package.json
  apps/orders/package.json
  apps/price_lists/package.json
  apps/promotions/package.json
  apps/returns/package.json
  apps/shipments/package.json
  apps/sku_lists/package.json
  apps/skus/package.json
  apps/stock_transfers/package.json
  apps/subscriptions/package.json
  apps/tags/package.json
  apps/webhooks/package.json
  lerna.json
  packages/common/package.json
  packages/index/package.json
Labels: ignore-for-release

#196 Fix redirect routes behavior
  apps/bundles/src/App.tsx
  apps/customers/src/pages/Home.tsx
  apps/gift_cards/src/pages/Home.tsx
  apps/sku_lists/src/App.tsx
  apps/skus/src/App.tsx
  apps/subscriptions/src/App.tsx
  apps/tags/src/App.tsx
Labels: bug

#198 Hide packing custom form if shipment has same origin and destination country
  apps/shipments/src/components/FormPacking.tsx
  apps/shipments/src/components/FormPackingMoreOptions.tsx
Labels: enhancement

#197 Enable `stock_line_items` relationship in shipment exports
  apps/exports/src/data/relationships.ts
Labels: enhancement

#199 v2.12.0
  apps/bundles/package.json
  apps/customers/package.json
  apps/exports/package.json
  apps/gift_cards/package.json
  apps/shipments/package.json
  apps/sku_lists/package.json
  apps/skus/package.json
  apps/subscriptions/package.json
  apps/tags/package.json
  lerna.json
Labels: ignore-for-release

#200 Show correct sales channel used in an already generated link
  apps/orders/src/hooks/useGetCheckoutLink.tsx
  apps/orders/src/pages/LinkDetails.tsx
Labels: bug

#201 v2.12.1
  apps/orders/package.json
  lerna.json
Labels: ignore-for-release
