Repository commercelayer/dashboard-apps, pull requests merged in 2025-07, with the labels that each got.

#299 v3.9.0
  apps/bundles/package.json
  apps/customers/package.json
  apps/exports/package.json
  apps/gift_cards/package.json
  apps/imports/package.json
  apps/inventory/package.json
  apps/my_sample_app/package.json
  apps/orders/package.json
  apps/price_lists/package.json
  apps/promotions/package.json
  apps/returns/package.json
  apps/shipments/package.json
  apps/sku_lists/package.json
  apps/skus/package.json
  apps/stock_transfers/package.json
  apps/subscriptions/package.json
  apps/tags/package.json
  apps/webhooks/package.json
  lerna.json
  packages/common/package.json
  packages/index/package.json
Labels: ignore-for-release

#298 Enable custom fields subset for orders export
  apps/exports/src/components/Form/index.tsx
  apps/exports/src/components/Form/types.d.ts
  apps/exports/src/data/fields.ts
  apps/exports/src/pages/NewExportPage.tsx
Labels: enhancement

#302 Add filters to export list
  apps/exports/src/App.tsx
  apps/exports/src/components/List/Provider.tsx
  apps/exports/src/data/filters.ts
  apps/exports/src/data/routes.ts
  apps/exports/src/pages/Filters.tsx
  apps/exports/src/pages/ListPage.tsx
Labels: enhancement

#309 Update `app-elements` package to latest version
  apps/bundles/package.json
  apps/customers/package.json
  apps/exports/package.json
  apps/gift_cards/package.json
  apps/imports/package.json
  apps/inventory/package.json
  apps/my_sample_app/package.json
  apps/orders/package.json
  apps/price_lists/package.json
  apps/promotions/package.json
  apps/returns/package.json
  apps/shipments/package.json
  apps/sku_lists/package.json
  apps/skus/package.json
  apps/stock_transfers/package.json
  apps/subscriptions/package.json
  apps/tags/package.json
  apps/webhooks/package.json
  packages/common/package.json
  packages/index/package.json
  pnpm-lock.yaml
Labels: enhancement

#310 v3.10.0
  apps/bundles/package.json
  apps/customers/package.json
  apps/exports/package.json
  apps/gift_cards/package.json
  apps/imports/package.json
  apps/inventory/package.json
  apps/my_sample_app/package.json
  apps/orders/package.json
  apps/price_lists/package.json
  apps/promotions/package.json
  apps/returns/package.json
  apps/shipments/package.json
  apps/sku_lists/package.json
  apps/skus/package.json
  apps/stock_transfers/package.json
  apps/subscriptions/package.json
  apps/tags/package.json
  apps/webhooks/package.json
  lerna.json
  packages/app-builder/package.json
  packages/common/package.json
  packages/index/package.json
Labels: ignore-for-release

#312 Update all dependencies to the latest major
  .circleci/config.yml
  .ncurc.js
  .npmrc
  apps/bundles/package.json
  apps/customers/package.json
  apps/customers/src/components/CustomerAnonymization.tsx
  apps/customers/src/hooks/useCustomerCanBeAnonymized.tsx
  apps/customers/src/hooks/useCustomerDeleteOverlay.tsx
  apps/exports/package.json
  apps/gift_cards/package.json
  apps/imports/package.json
  apps/inventory/package.json
  apps/my_sample_app/package.json
  apps/orders/package.json
  apps/orders/src/mocks/resources/shipping_methods.ts
  apps/price_lists/package.json
  apps/promotions/package.json
  apps/returns/package.json
  apps/returns/src/mocks/resources/shipping_methods.ts
  apps/shipments/package.json
  apps/shipments/src/mocks/resources/shipping_methods.ts
  apps/sku_lists/package.json
  apps/skus/package.json
  apps/stock_transfers/package.json
  apps/stock_transfers/src/mocks/resources/shipping_methods.ts
  apps/subscriptions/package.json
  apps/tags/package.json
  apps/webhooks/package.json
  package.json
  packages/app-builder/package.json
  packages/app-builder/vite.config.js
  packages/common/package.json
  packages/index/package.json
  pnpm-lock.yaml
  replace-react.mjs
Labels: dependencies

#279 Implement new RuleEngine component in the promotion app
  apps/promotions/src/components/FlexRuleBuilder.tsx
  apps/promotions/src/components/PromotionForm.tsx
  apps/promotions/src/data/formConverters/promotion.ts
  apps/promotions/src/data/promotions/config.tsx
  apps/promotions/src/data/promotions/configs/flex_promotions.tsx
  apps/promotions/src/data/promotions/configs/promotions.tsx
  apps/promotions/src/main.tsx
  apps/promotions/src/mocks/index.ts
  apps/promotions/src/mocks/resources/flex_promotions.ts
  apps/promotions/src/pages/NewSelectTypePage.tsx
  apps/promotions/src/pages/PromotionDetailsPage.tsx
Labels: enhancement

#315 v3.11.0
  apps/bundles/package.json
  apps/customers/package.json
  apps/exports/package.json
  apps/gift_cards/package.json
  apps/imports/package.json
  apps/inventory/package.json
  apps/my_sample_app/package.json
  apps/orders/package.json
  apps/price_lists/package.json
  apps/promotions/package.json
  apps/returns/package.json
  apps/shipments/package.json
  apps/sku_lists/package.json
  apps/skus/package.json
  apps/stock_transfers/package.json
  apps/subscriptions/package.json
  apps/tags/package.json
  apps/webhooks/package.json
  lerna.json
  packages/common/package.json
  packages/index/package.json
Labels: ignore-for-release

#317 Add filters in import list
  apps/imports/src/App.tsx
  apps/imports/src/components/List/Provider.tsx
  apps/imports/src/data/filters.ts
  apps/imports/src/data/resources.ts
  apps/imports/src/data/routes.ts
  apps/imports/src/pages/Filters.tsx
  apps/imports/src/pages/ListPage.tsx
  apps/imports/src/pages/ResourceSelectorPage.tsx
Labels: enhancement

#319 v3.11.1
  apps/bundles/package.json
  apps/customers/package.json
  apps/exports/package.json
  apps/gift_cards/package.json
  apps/imports/package.json
  apps/inventory/package.json
  apps/my_sample_app/package.json
  apps/orders/package.json
  apps/price_lists/package.json
  apps/promotions/package.json
  apps/returns/package.json
  apps/shipments/package.json
  apps/sku_lists/package.json
  apps/skus/package.json
  apps/stock_transfers/package.json
  apps/subscriptions/package.json
  apps/tags/package.json
  apps/webhooks/package.json
  lerna.json
  packages/common/package.json
  packages/index/package.json
Labels: ignore-for-release

#320 Optimize API calls in SkuListDetailsAddItems component
  apps/sku_lists/src/pages/SkuListDetailsAddItems.tsx
Labels: bug

#321 v3.11.2
  apps/sku_lists/package.json
  lerna.json
Labels: ignore-for-release
