Repository commercelayer/dashboard-apps, pull requests merged in 2025-09, with the labels that each got.

#329 Update app-elements + remove price_lists management from the prices app
  apps/bundles/package.json
  apps/customers/package.json
  apps/exports/package.json
  apps/gift_cards/package.json
  apps/imports/package.json
  apps/inventory/package.json
  apps/inventory/src/components/ListEmptyStateStockLocations.tsx
  apps/my_sample_app/package.json
  apps/orders/package.json
  apps/price_lists/package.json
  apps/price_lists/src/App.tsx
  apps/price_lists/src/components/PriceListForm.tsx
  apps/price_lists/src/data/routes.ts
  apps/price_lists/src/pages/Home.tsx
  apps/price_lists/src/pages/PriceListEdit.tsx
  apps/price_lists/src/pages/PriceListNew.tsx
  apps/price_lists/src/pages/PricesList.tsx
  apps/promotions/package.json
  apps/promotions/src/components/FlexRuleBuilder.tsx
  apps/returns/package.json
  apps/shipments/package.json
  apps/sku_lists/package.json
  apps/skus/package.json
  apps/stock_transfers/package.json
  apps/subscriptions/package.json
  apps/tags/package.json
  apps/webhooks/package.json
  packages/common/package.json
  packages/index/package.json
  packages/index/src/appList.js
  packages/index/src/apps.ts
  packages/index/src/pages/HomePage.tsx
  pnpm-lock.yaml
Labels: enhancement

#335 v3.11.5
  apps/bundles/package.json
  apps/orders/package.json
  apps/returns/package.json
  apps/sku_lists/package.json
  apps/skus/package.json
  lerna.json
  packages/common/package.json
Labels: ignore-for-release

#336 Remove `return_line_items_line_item_sku_code` predicate from app-returns search filter
  apps/returns/src/data/filters.ts
Labels: bug

#340 v3.11.6
  apps/bundles/package.json
  apps/customers/package.json
  apps/exports/package.json
  apps/gift_cards/package.json
  apps/imports/package.json
  apps/inventory/package.json
  apps/my_sample_app/package.json
  apps/orders/package.json
  apps/price_lists/package.json
  apps/promotions/package.json
  apps/returns/package.json
  apps/shipments/package.json
  apps/sku_lists/package.json
  apps/skus/package.json
  apps/stock_transfers/package.json
  apps/subscriptions/package.json
  apps/tags/package.json
  apps/webhooks/package.json
  lerna.json
  packages/app-builder/package.json
  packages/common/package.json
  packages/index/package.json
Labels: ignore-for-release

#334 Promotion rules are now restored after being saved
  apps/promotions/src/components/FlexRuleBuilder.tsx
Labels: bug
