Repository commercelayer/dashboard-apps, pull requests merged in 2025-02, with the labels that each got.

#203 v2.13.0
  apps/bundles/package.json
  apps/customers/package.json
  apps/exports/package.json
  apps/gift_cards/package.json
  apps/imports/package.json
  apps/inventory/package.json
  apps/orders/package.json
  apps/price_lists/package.json
  apps/promotions/package.json
  apps/returns/package.json
  apps/shipments/package.json
  apps/sku_lists/package.json
  apps/skus/package.json
  apps/stock_transfers/package.json
  apps/subscriptions/package.json
  apps/tags/package.json
  apps/webhooks/package.json
  lerna.json
  packages/common/package.json
  packages/index/package.json
Labels: ignore-for-release

#205 Set proper condition in new order page
  apps/orders/src/pages/OrderNew.tsx
Labels: bug

#206 v2.13.1
  apps/orders/package.json
  lerna.json
Labels: ignore-for-release

#204 Increase paginated coupons per page in promotions
  apps/promotions/src/pages/CouponListPage.tsx
Labels: enhancement

#208 Drop usage of shouldRender method
  apps/customers/src/components/CustomerForm.tsx
  apps/customers/src/pages/CustomerDetails.tsx
  apps/orders/src/components/NewOrder/EditOrderStep.tsx
  apps/orders/src/pages/Home.tsx
  apps/orders/src/pages/OrderDetails.tsx
  apps/orders/src/pages/OrderNew.tsx
  apps/returns/src/pages/ReturnDetails.tsx
  apps/shipments/src/pages/ShipmentDetails.tsx
Labels: enhancement

#209 Update elements to latest version
  apps/bundles/package.json
  apps/customers/package.json
  apps/customers/src/hooks/useCustomerDeleteOverlay.tsx
  apps/exports/package.json
  apps/gift_cards/package.json
  apps/imports/package.json
  apps/inventory/package.json
  apps/orders/package.json
  apps/orders/src/pages/LinkDetails.tsx
  apps/price_lists/package.json
  apps/price_lists/src/components/PriceListForm.tsx
  apps/promotions/package.json
  apps/promotions/src/pages/NewSelectTypePage.tsx
  apps/returns/package.json
  apps/shipments/package.json
  apps/sku_lists/package.json
  apps/skus/package.json
  apps/stock_transfers/package.json
  apps/subscriptions/package.json
  apps/tags/package.json
  apps/webhooks/package.json
  packages/common/package.json
  packages/common/src/pages/LinkDetailsPage.tsx
  packages/index/package.json
  packages/index/src/App.tsx
  pnpm-lock.yaml
Labels: enhancement

#210 Add order returns in exports app
  apps/exports/src/data/relationships.ts
Labels: enhancement

#211 v2.14.0
  apps/bundles/package.json
  apps/customers/package.json
  apps/exports/package.json
  apps/gift_cards/package.json
  apps/imports/package.json
  apps/inventory/package.json
  apps/orders/package.json
  apps/price_lists/package.json
  apps/promotions/package.json
  apps/returns/package.json
  apps/shipments/package.json
  apps/sku_lists/package.json
  apps/skus/package.json
  apps/stock_transfers/package.json
  apps/subscriptions/package.json
  apps/tags/package.json
  apps/webhooks/package.json
  lerna.json
  packages/common/package.json
  packages/index/package.json
Labels: ignore-for-release

#212 Add `returns` resource type in exports app
  apps/exports/@typing/Resources.d.ts
  apps/exports/src/data/relationships.ts
  apps/exports/src/data/resources.ts
Labels: enhancement

#215 v2.14.1
  apps/bundles/package.json
  apps/customers/package.json
  apps/exports/package.json
  apps/gift_cards/package.json
  apps/imports/package.json
  apps/inventory/package.json
  apps/orders/package.json
  apps/price_lists/package.json
  apps/promotions/package.json
  apps/returns/package.json
  apps/shipments/package.json
  apps/sku_lists/package.json
  apps/skus/package.json
  apps/stock_transfers/package.json
  apps/subscriptions/package.json
  apps/tags/package.json
  apps/webhooks/package.json
  lerna.json
  packages/common/package.json
  packages/index/package.json
Labels: ignore-for-release

#216 Rename Home title of Price lists app
  apps/price_lists/src/pages/Home.tsx
Labels: enhancement

#217 Fix validation of SKUList rule for minimum qty input
  apps/promotions/src/data/ruleBuilder/form/validator.tsx
Labels: bug

#219 Add attachments
  apps/bundles/package.json
  apps/customers/package.json
  apps/customers/src/pages/CustomerDetails.tsx
  apps/exports/package.json
  apps/gift_cards/package.json
  apps/imports/package.json
  apps/inventory/package.json
  apps/orders/package.json
  apps/orders/src/pages/OrderDetails.tsx
  apps/price_lists/package.json
  apps/promotions/package.json
  apps/returns/package.json
  apps/returns/src/pages/ReturnDetails.tsx
  apps/shipments/package.json
  apps/shipments/src/pages/ShipmentDetails.tsx
  apps/sku_lists/package.json
  apps/skus/package.json
  apps/stock_transfers/package.json
  apps/subscriptions/package.json
  apps/tags/package.json
  apps/webhooks/package.json
  packages/common/package.json
  packages/index/package.json
  pnpm-lock.yaml
Labels: enhancement

#220 v2.15.0
  apps/bundles/package.json
  apps/customers/package.json
  apps/exports/package.json
  apps/gift_cards/package.json
  apps/imports/package.json
  apps/inventory/package.json
  apps/orders/package.json
  apps/price_lists/package.json
  apps/promotions/package.json
  apps/returns/package.json
  apps/shipments/package.json
  apps/sku_lists/package.json
  apps/skus/package.json
  apps/stock_transfers/package.json
  apps/subscriptions/package.json
  apps/tags/package.json
  apps/webhooks/package.json
  lerna.json
  packages/common/package.json
  packages/index/package.json
Labels: ignore-for-release

#221 Fix variable key of order editing translation
  apps/orders/src/components/OrderSummary/hooks/useSummaryRows.tsx
Labels: bug

#222 v3.0.0
  apps/bundles/package.json
  apps/customers/package.json
  apps/exports/package.json
  apps/gift_cards/package.json
  apps/imports/package.json
  apps/inventory/package.json
  apps/orders/package.json
  apps/price_lists/package.json
  apps/promotions/package.json
  apps/returns/package.json
  apps/shipments/package.json
  apps/sku_lists/package.json
  apps/skus/package.json
  apps/stock_transfers/package.json
  apps/subscriptions/package.json
  apps/tags/package.json
  apps/webhooks/package.json
  lerna.json
  packages/app-builder/package.json
  packages/common/package.json
  packages/index/package.json
Labels: ignore-for-release

#224 v3.0.1
  apps/shipments/package.json
  lerna.json
Labels: ignore-for-release

#225 Improvement shipment list loading state
  apps/shipments/src/mocks/resources/shipments.ts
Labels: bug
